image: node:24

stages:
  - test

e2e-tests:
  stage: test

  script:
    - yarn install
    - npx playwright install --with-deps
    - yarn run e2e

  artifacts:
    when: always
    paths:
      - allure-results/
      - playwright-report/
      - test-results/
      - results.xml
    expire_in: 10 days